name: Build

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt

    - name: Edit package.json
      run: |
        sed -i 's/\("version": *"[^"]*\)\("\)/\1+${{ github.sha }}\2/' jssrc/package.json

    - name: Build package
      run: make dependencies build

    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.head_ref }}-${{ github.sha }}
        path: pysrc/dist/
